# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: iperf3 Server
version: "1.0.0"
slug: iperf3
description: iperf3 Server on Homeassistant
url: "https://github.com/dikt1338/dikt-home-assistant-addons/tree/main/iperf3"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
